# Generated by Django 6.1 on 2026-10-06 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address')),
                ('password', models.CharField(db_column='password_hash', max_length=255, verbose_name='password')),
                ('role', models.CharField(choices=[('candidate', 'Candidate'), ('mentor', 'Mentor'), ('admin', 'Admin')], default='candidate', help_text='Designates role of the user (candidate, mentor, admin).', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether this user has verified their email/account.', verbose_name='verified')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the Django admin site.', verbose_name='staff status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('domain', 'Domain'), ('soft', 'Soft'), ('tool', 'Tool')], default='technical', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill Master',
                'verbose_name_plural': 'Skills Master',
                'db_table': 'skills_master',
                'ordering': ['canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='UserGamificationProfile',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gamification', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_xp', models.IntegerField(default=0)),
                ('current_streak_days', models.IntegerField(default=0)),
                ('longest_streak_days', models.IntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('tier_badge', models.CharField(default='Bronze', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gamification Profile',
                'verbose_name_plural': 'Gamification Profiles',
                'db_table': 'user_gamification_profile',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('college_tier', models.CharField(blank=True, max_length=20, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_discipline', models.CharField(blank=True, max_length=150, null=True)),
                ('current_status', models.CharField(blank=True, max_length=50, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('current_semester', models.CharField(blank=True, max_length=20, null=True)),
                ('experience_months', models.IntegerField(default=0)),
                ('target_role', models.CharField(blank=True, max_length=150, null=True)),
                ('target_company_types', models.JSONField(blank=True, default=list)),
                ('raw_resume_url', models.TextField(blank=True, null=True)),
                ('github_url', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=255, null=True)),
                ('portfolio_url', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('source', models.CharField(choices=[('cv', 'CV'), ('github', 'GitHub'), ('quiz', 'Quiz'), ('interview', 'Interview'), ('self', 'Self')], default='self', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.RESTRICT, related_name='user_skills', to='accounts.skillmaster')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Skill',
                'verbose_name_plural': 'User Skills',
                'db_table': 'user_skills',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
