# Generated by Django 6.1 on 2026-10-04 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume_title', models.CharField(max_length=200)),
                ('version_number', models.IntegerField(default=1)),
                ('mode', models.CharField(choices=[('reformat', 'Reformat'), ('generate', 'Generate'), ('optimize', 'Optimize')], default='generate', max_length=20)),
                ('template_name', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('technical', 'Technical')], default='modern', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume Master',
                'verbose_name_plural': 'Resumes Master',
                'db_table': 'resumes_master',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeCompilation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latex_source_code', models.TextField()),
                ('compiled_pdf_url', models.TextField(blank=True, null=True)),
                ('compilation_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('compiler_log', models.TextField(blank=True, null=True)),
                ('compiled_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='compilations', to='resumes.resumemaster')),
            ],
            options={
                'verbose_name': 'Resume Compilation',
                'verbose_name_plural': 'Resume Compilations',
                'db_table': 'resume_compilations',
                'ordering': ['-compiled_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeStructuredContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_info', models.JSONField(blank=True, default=dict)),
                ('professional_summary', models.TextField(blank=True, null=True)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('publications_awards', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='structured_content', to='resumes.resumemaster')),
            ],
            options={
                'verbose_name': 'Resume Structured Content',
                'verbose_name_plural': 'Resume Structured Contents',
                'db_table': 'resume_structured_content',
            },
        ),
        migrations.CreateModel(
            name='TargetJobDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_jd_text', models.TextField()),
                ('jd_source_url', models.TextField(blank=True, null=True)),
                ('extracted_skills', models.JSONField(blank=True, default=list, null=True)),
                ('experience_required_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='target_jds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Target Job Description',
                'verbose_name_plural': 'Target Job Descriptions',
                'db_table': 'target_job_descriptions',
                'ordering': ['-parsed_at'],
            },
        ),
        migrations.AddField(
            model_name='resumemaster',
            name='target_jd',
            field=models.ForeignKey(blank=True, db_column='target_jd_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.targetjobdescription'),
        ),
        migrations.CreateModel(
            name='ResumeATSAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_ats_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('format_safety_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('section_headers_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('keyword_match_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('bullet_quant_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('actionable_recommendations', models.JSONField(blank=True, default=list)),
                ('audited_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='ats_audits', to='resumes.resumemaster')),
                ('target_jd', models.ForeignKey(blank=True, db_column='target_jd_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.targetjobdescription')),
            ],
            options={
                'verbose_name': 'Resume ATS Audit',
                'verbose_name_plural': 'Resume ATS Audits',
                'db_table': 'resume_ats_audits',
                'ordering': ['-audited_at'],
            },
        ),
    ]
