# Generated by Django 6.1 on 2026-10-04 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIEvaluationFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluated_by_model', models.CharField(blank=True, max_length=100, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('content_accuracy_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('depth_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('star_structure_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('code_quality_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('communication_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('detailed_feedback', models.TextField()),
                ('missed_concepts', models.JSONField(blank=True, default=list, null=True)),
                ('strengths', models.JSONField(blank=True, default=list, null=True)),
                ('remediation_suggestions', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Evaluation Feedback',
                'verbose_name_plural': 'AI Evaluations Feedback',
                'db_table': 'ai_evaluations_feedback',
            },
        ),
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.IntegerField()),
                ('round_format', models.CharField(choices=[('MCQ', 'MCQ'), ('Descriptive', 'Descriptive'), ('Coding', 'Coding'), ('Voice', 'Voice')], default='MCQ', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('time_limit_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('round_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Interview Round',
                'verbose_name_plural': 'Interview Rounds',
                'db_table': 'interview_rounds',
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='InterviewScorecard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('radar_metrics_json', models.JSONField(blank=True, default=dict, null=True)),
                ('technical_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('communication_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('problem_solving_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_executive_summary', models.TextField(blank=True, null=True)),
                ('actionable_takeaways', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interview Scorecard',
                'verbose_name_plural': 'Interview Scorecards',
                'db_table': 'interview_scorecards',
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('mock', 'Mock'), ('domain', 'Domain'), ('remediation', 'Remediation')], default='mock', max_length=20)),
                ('session_title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_rounds', models.IntegerField(default=4)),
                ('current_round', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interview Session',
                'verbose_name_plural': 'Interview Sessions',
                'db_table': 'interview_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInterviewResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_format', models.CharField(blank=True, choices=[('MCQ', 'MCQ'), ('Descriptive', 'Descriptive'), ('Coding', 'Coding'), ('Voice', 'Voice')], max_length=20, null=True)),
                ('user_submission_text', models.TextField(blank=True, null=True)),
                ('code_output_stdout', models.TextField(blank=True, null=True)),
                ('code_output_stderr', models.TextField(blank=True, null=True)),
                ('audio_recording_url', models.TextField(blank=True, null=True)),
                ('stt_transcription_text', models.TextField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Interview Response',
                'verbose_name_plural': 'User Interview Responses',
                'db_table': 'user_interview_responses',
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_order', models.IntegerField()),
                ('format', models.CharField(choices=[('MCQ', 'MCQ'), ('Descriptive', 'Descriptive'), ('Coding', 'Coding'), ('Voice', 'Voice')], default='MCQ', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('competency_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('bloom_level', models.CharField(blank=True, choices=[('Remember', 'Remember'), ('Understand', 'Understand'), ('Apply', 'Apply'), ('Analyze', 'Analyze'), ('Evaluate', 'Evaluate'), ('Create', 'Create')], max_length=20, null=True)),
                ('question_text', models.TextField()),
                ('options_json', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('ideal_reference_answer', models.TextField(blank=True, null=True)),
                ('coding_starter_code', models.TextField(blank=True, null=True)),
                ('test_cases_json', models.JSONField(blank=True, null=True)),
                ('evaluation_rubric_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(db_column='round_id', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interviewround')),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'db_table': 'interview_questions',
                'ordering': ['question_order'],
            },
        ),
    ]
