# Generated by Django 6.1 on 2026-10-04 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='target_role',
            field=models.ForeignKey(blank=True, db_column='target_role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobroletaxonomy'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewscorecard',
            name='session',
            field=models.OneToOneField(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='scorecard', to='interviews.interviewsession'),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='session',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='interviews.interviewsession'),
        ),
        migrations.AddField(
            model_name='userinterviewresponse',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interviews.interviewquestion'),
        ),
        migrations.AddField(
            model_name='userinterviewresponse',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='interview_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aievaluationfeedback',
            name='response',
            field=models.OneToOneField(db_column='response_id', on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluation', to='interviews.userinterviewresponse'),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['round'], name='idx_interview_questions_round'),
        ),
        migrations.AddIndex(
            model_name='interviewround',
            index=models.Index(fields=['session'], name='idx_interview_rounds_session'),
        ),
        migrations.AddIndex(
            model_name='userinterviewresponse',
            index=models.Index(fields=['question'], name='idx_user_interview_responses_q'),
        ),
    ]
