# Generated by Django 6.0.9 on 2026-10-08 05:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRoleTaxonomy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_title', models.CharField(max_length=150)),
                ('role_slug', models.SlugField(max_length=150, unique=True)),
                ('department_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('seniority_level', models.CharField(blank=True, max_length=50, null=True)),
                ('standard_required_skills', models.JSONField(blank=True, help_text='List of required canonical skill names', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Role Taxonomy',
                'verbose_name_plural': 'Job Roles Taxonomy',
                'db_table': 'job_roles_taxonomy',
                'ordering': ['role_title'],
            },
        ),
        migrations.CreateModel(
            name='SkillGapReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('readiness_level', models.CharField(choices=[('Ready', 'Ready'), ('Minor Gaps', 'Minor Gaps'), ('Needs Upskilling', 'Needs Upskilling'), ('Significant Gaps', 'Significant Gaps')], default='Needs Upskilling', max_length=30)),
                ('total_required_skills', models.IntegerField(default=0)),
                ('skills_matched_count', models.IntegerField(default=0)),
                ('skills_gap_count', models.IntegerField(default=0)),
                ('analysis_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gap_reports', to='skill_gap.jobroletaxonomy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Gap Report',
                'verbose_name_plural': 'Skill Gap Reports',
                'db_table': 'skill_gap_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillGapItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_current_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('required_score', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('gap_severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('recommended_action', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_occurrences', to='accounts.skillmaster')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_items', to='skill_gap.skillgapreport')),
            ],
            options={
                'verbose_name': 'Skill Gap Item',
                'verbose_name_plural': 'Skill Gap Items',
                'db_table': 'skill_gap_items',
                'ordering': ['-gap_severity', 'skill__canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='TargetJobDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_jd_text', models.TextField()),
                ('jd_source_url', models.TextField(blank=True, null=True)),
                ('extracted_skills', models.JSONField(blank=True, help_text='JSON extracted skills from LLM', null=True)),
                ('experience_required_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_jds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Target Job Description',
                'verbose_name_plural': 'Target Job Descriptions',
                'db_table': 'target_job_descriptions',
                'ordering': ['-parsed_at'],
            },
        ),
        migrations.AddField(
            model_name='skillgapreport',
            name='target_jd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gap_reports', to='skill_gap.targetjobdescription'),
        ),
        migrations.CreateModel(
            name='RoleSkillRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('importance', models.CharField(choices=[('mandatory', 'Mandatory'), ('preferred', 'Preferred')], default='mandatory', max_length=20)),
                ('benchmark_score_min', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('weightage', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='skill_gap.jobroletaxonomy')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='accounts.skillmaster')),
            ],
            options={
                'verbose_name': 'Role Skill Requirement',
                'verbose_name_plural': 'Role Skill Requirements',
                'db_table': 'role_skill_requirements',
                'unique_together': {('role', 'skill')},
            },
        ),
    ]
