# Generated by Django 6.0.9 on 2026-10-08 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('skill_gap', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('lab', 'Lab')], default='video', max_length=20)),
                ('video_embed_url', models.TextField(blank=True, null=True)),
                ('pdf_material_url', models.TextField(blank=True, null=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('xp_reward', models.IntegerField(default=50)),
                ('tags', models.JSONField(blank=True, help_text='List of technology/competency tags', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DynamicLearningRoadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('target_role_goal', models.CharField(blank=True, max_length=150, null=True)),
                ('total_stages', models.IntegerField(default=8)),
                ('completed_stages', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gap_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmaps', to='skill_gap.skillgapreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dynamic Learning Roadmap',
                'verbose_name_plural': 'Dynamic Learning Roadmaps',
                'db_table': 'dynamic_learning_roadmaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('stage_type', models.CharField(choices=[('course', 'Course'), ('assessment', 'Assessment')], default='course', max_length=20)),
                ('xp_points', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_usages', to='learning_hub.course')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='learning_hub.dynamiclearningroadmap')),
                ('target_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_stages', to='accounts.skillmaster')),
            ],
            options={
                'verbose_name': 'Roadmap Stage',
                'verbose_name_plural': 'Roadmap Stages',
                'db_table': 'roadmap_stages',
                'ordering': ['roadmap', 'stage_number'],
                'unique_together': {('roadmap', 'stage_number')},
            },
        ),
        migrations.CreateModel(
            name='SpacedRepetitionSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_interval_days', models.IntegerField(default=1)),
                ('repetition_count', models.IntegerField(default=0)),
                ('ease_factor', models.DecimalField(decimal_places=2, default=2.5, max_digits=3)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_due_at', models.DateTimeField()),
                ('retention_streak', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetition_schedules', to='accounts.skillmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetition_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spaced Repetition Schedule',
                'verbose_name_plural': 'Spaced Repetition Schedules',
                'db_table': 'spaced_repetition_schedules',
                'ordering': ['next_review_due_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('watch_time_seconds', models.IntegerField(default=0)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='learning_hub.course')),
                ('roadmap_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_records', to='learning_hub.roadmapstage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Course Progress',
                'verbose_name_plural': 'User Course Progresses',
                'db_table': 'user_course_progress',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
