# Generated by Django 6.1 on 2026-10-04 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('domain', 'Domain'), ('soft', 'Soft'), ('tool', 'Tool')], default='technical', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill Master',
                'verbose_name_plural': 'Skills Master',
                'db_table': 'skills_master',
                'ordering': ['canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias_name', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='skills.skillmaster')),
            ],
            options={
                'verbose_name': 'Skill Alias',
                'verbose_name_plural': 'Skill Aliases',
                'db_table': 'skill_aliases',
            },
        ),
        migrations.CreateModel(
            name='RoleSkillRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('importance', models.CharField(choices=[('mandatory', 'Mandatory'), ('preferred', 'Preferred')], default='mandatory', max_length=20)),
                ('benchmark_score_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weightage', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='jobs.jobroletaxonomy')),
                ('skill', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.RESTRICT, related_name='role_requirements', to='skills.skillmaster')),
            ],
            options={
                'verbose_name': 'Role Skill Requirement',
                'verbose_name_plural': 'Role Skill Requirements',
                'db_table': 'role_skill_requirements',
                'unique_together': {('role', 'skill')},
            },
        ),
    ]
