# Generated by Django 6.1 on 2026-10-04 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHackathonListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('hackathon', 'Hackathon'), ('sprint', 'Sprint'), ('webinar', 'Webinar'), ('hiring_challenge', 'Hiring Challenge')], default='hackathon', max_length=30)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_online', models.BooleanField(default=True)),
                ('themes_tags', models.JSONField(blank=True, default=list)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('prize_pool', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_url', models.TextField()),
                ('source_platform', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event & Hackathon Listing',
                'verbose_name_plural': 'Event & Hackathon Listings',
                'db_table': 'event_hackathon_listings',
            },
        ),
        migrations.CreateModel(
            name='JobRoleTaxonomy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_title', models.CharField(max_length=150)),
                ('role_slug', models.SlugField(max_length=150, unique=True)),
                ('department_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('seniority_level', models.CharField(blank=True, max_length=50, null=True)),
                ('standard_required_skills', models.JSONField(blank=True, default=list, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Role Taxonomy',
                'verbose_name_plural': 'Job Roles Taxonomy',
                'db_table': 'job_roles_taxonomy',
                'ordering': ['role_title'],
            },
        ),
        migrations.CreateModel(
            name='SkillGapItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_current_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('required_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gap_severity', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20, null=True)),
                ('recommended_action', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill Gap Item',
                'verbose_name_plural': 'Skill Gap Items',
                'db_table': 'skill_gap_items',
            },
        ),
        migrations.CreateModel(
            name='SkillGapReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('readiness_level', models.CharField(blank=True, choices=[('job_ready', 'Job Ready'), ('minor_gaps', 'Minor Gaps'), ('critical_gaps', 'Critical Gaps')], max_length=20, null=True)),
                ('total_required_skills', models.IntegerField(blank=True, null=True)),
                ('skills_matched_count', models.IntegerField(blank=True, null=True)),
                ('skills_gap_count', models.IntegerField(blank=True, null=True)),
                ('analysis_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill Gap Report',
                'verbose_name_plural': 'Skill Gap Reports',
                'db_table': 'skill_gap_reports',
            },
        ),
        migrations.CreateModel(
            name='UserJobMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skill_match_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('experience_match', models.BooleanField(blank=True, null=True)),
                ('match_breakdown_json', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('saved', 'Saved'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='suggested', max_length=20)),
                ('applied_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Job Match',
                'verbose_name_plural': 'User Job Matches',
                'db_table': 'user_job_matches',
            },
        ),
        migrations.CreateModel(
            name='UserOpportunityBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Opportunity Bookmark',
                'verbose_name_plural': 'User Opportunity Bookmarks',
                'db_table': 'user_opportunity_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='GithubPortfolioAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_username', models.CharField(blank=True, max_length=100, null=True)),
                ('analyzed_repos_count', models.IntegerField(default=0)),
                ('detected_languages', models.JSONField(blank=True, default=list, null=True)),
                ('detected_frameworks', models.JSONField(blank=True, default=list, null=True)),
                ('inferred_skills', models.JSONField(blank=True, default=list, null=True)),
                ('commit_activity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('raw_insights', models.JSONField(blank=True, default=dict, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='github_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Portfolio Analysis',
                'verbose_name_plural': 'GitHub Portfolio Analyses',
                'db_table': 'github_portfolio_analyses',
            },
        ),
        migrations.CreateModel(
            name='JobAlertPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_keywords', models.JSONField(blank=True, default=list)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('preferred_job_types', models.JSONField(blank=True, default=list)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('notification_channels', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='job_alert_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Alert Preference',
                'verbose_name_plural': 'Job Alert Preferences',
                'db_table': 'job_alert_preferences',
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo_url', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('experience_min_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('experience_max_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='INR', max_length=10)),
                ('description_raw', models.TextField()),
                ('extracted_skills', models.JSONField(blank=True, default=list, null=True)),
                ('application_url', models.TextField()),
                ('deadline_date', models.DateTimeField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('source_platform', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Listing',
                'verbose_name_plural': 'Job Listings',
                'db_table': 'job_listings',
                'ordering': ['-date_posted', '-scraped_at'],
                'indexes': [models.Index(fields=['is_active'], name='idx_job_listings_active')],
            },
        ),
    ]
