# Generated by Django 6.1 on 2026-10-04 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgapitem',
            name='skill',
            field=models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.RESTRICT, related_name='gap_items', to='skills.skillmaster'),
        ),
        migrations.AddField(
            model_name='skillgapreport',
            name='target_jd',
            field=models.ForeignKey(blank=True, db_column='target_jd_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.targetjobdescription'),
        ),
        migrations.AddField(
            model_name='skillgapreport',
            name='target_role',
            field=models.ForeignKey(blank=True, db_column='target_role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobroletaxonomy'),
        ),
        migrations.AddField(
            model_name='skillgapreport',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillgapitem',
            name='report',
            field=models.ForeignKey(db_column='report_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jobs.skillgapreport'),
        ),
        migrations.AddField(
            model_name='userjobmatch',
            name='job_listing',
            field=models.ForeignKey(db_column='job_listing_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_matches', to='jobs.joblisting'),
        ),
        migrations.AddField(
            model_name='userjobmatch',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useropportunitybookmark',
            name='event',
            field=models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.eventhackathonlisting'),
        ),
        migrations.AddField(
            model_name='useropportunitybookmark',
            name='job',
            field=models.ForeignKey(blank=True, db_column='job_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.joblisting'),
        ),
        migrations.AddField(
            model_name='useropportunitybookmark',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='skillgapitem',
            unique_together={('report', 'skill')},
        ),
        migrations.AddIndex(
            model_name='userjobmatch',
            index=models.Index(fields=['user', '-match_percentage'], name='idx_user_job_matches_user'),
        ),
    ]
